version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "mailingdb"
      POSTGRES_USER: "userdb"
      POSTGRES_PASSWORD: "passwd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - mailing-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mailing:
    image: python:latest
    volumes:
      - ../model:/app/model
      - ../view:/app/view
      - ../controller:/app/controller
      - ../main.py:/app/main.py
      - ../requirements.txt:/app/requirements.txt
    command: sh -c "cd /app && pip install -r requirements.txt && python main.py"
    depends_on:
      - postgres
volumes:
  mailing-data:
